### ISSUE TITLE
下载出错

### ISSUE THREAD

**Issue by i0sdev** [sk1418/zhuaxia#12]
下载这个歌单 http://music.163.com/#/playlist?id=42626737 出错
```
Traceback (most recent call last):
  File "/usr/local/bin/zx", line 5, in <module>
    pkg_resources.run_script('zhuaxia==2.4.0', 'zx')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 492, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1350, in run_script
    execfile(script_filename, namespace, namespace)
  File "/Library/Python/2.7/site-packages/zhuaxia-2.4.0-py2.7.egg/EGG-INFO/scripts/zx", line 110, in <module>
    commander.shall_I_begin(inUrl, is_hq=hq, need_proxy_pool = needProxyPool)
  File "/Library/Python/2.7/site-packages/zhuaxia-2.4.0-py2.7.egg/zhuaxia/commander.py", line 52, in shall_I_begin
    from_url_163(m163, in_str)
  File "/Library/Python/2.7/site-packages/zhuaxia-2.4.0-py2.7.egg/zhuaxia/commander.py", line 86, in from_url_163
    playlist = netease.NeteasePlayList(m163, url)
  File "/Library/Python/2.7/site-packages/zhuaxia-2.4.0-py2.7.egg/zhuaxia/netease.py", line 128, in __init__
    self.init_playlist()
  File "/Library/Python/2.7/site-packages/zhuaxia-2.4.0-py2.7.egg/zhuaxia/netease.py", line 134, in init_playlist
    song = NeteaseSong(self.handler, song_json=jsong)
  File "/Library/Python/2.7/site-packages/zhuaxia-2.4.0-py2.7.egg/zhuaxia/netease.py", line 54, in __init__
    self.init_by_json(song_json)
  File "/Library/Python/2.7/site-packages/zhuaxia-2.4.0-py2.7.egg/zhuaxia/netease.py", line 72, in init_by_json
    dfsId = js['mMusic']['dfsId']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by sk1418** [comment]
@i0sdev  原因:某些163歌曲没有128kbps 资源, 你的例子中是"仨人"这首歌有这个问题.

已在bleeding branch里修复. 你可以测试一下,如果确认修复请告知并关闭issue, 我会随后merge到master里.

**Comment by i0sdev** [comment]
ok 了，谢谢！
