### ISSUE TITLE
断线重试

### ISSUE THREAD

**Issue by lianxiangru** [sk1418/zhuaxia#21]
似乎下载项在connection reset by peer之后就再也不下载了，可以考虑加一个自动重试下载的feature

**Comment by sk1418** [comment]
能不能附带一个例子,或者链接, 能产生这个reset by peer错误的?

**Comment by lianxiangru** [comment]
不一定会出现在哪一个链接上，通常某些文件是下载到一半突然被断开连接。应该是网易的反爬机制。我开7个thread 平均每五分钟都有一些被reset

**Comment by lianxiangru** [comment]
@sk1418  附一个trackback
~~~python
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  保存目录:[/home/xiangru/Music] | 线程池:[7]
 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
                                                                   总进度[0/277]: [                                                            ] 0.5%
 =======================================================================================================================================================
                    ステレオポニー_泪のムコウ ~AIMI Acoustic Version - unplug.mp3 [================================                            ] 53.8%
                    きゃりーぱみゅぱみゅ_Candy Candy ［Extended Mix］ - remix.mp3 [==                                                          ] 4.1%
                                                         KOTOKO_Light My Fire.mp3 [=================================                           ] 56.7%
                                                           Kalafina_Lacrimosa.mp3 [                                                            ] 0.4%
                                                島谷ひとみ_Destiny -太陽の花-.mp3 [                                                            ] 1.5%
                                                                     AAA_MASK.mp3 [===========                                                 ] 18.7%
                                                      佐咲紗花_fly away t.p.s.mp3 [===                                                         ] 5.7%
 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/zhuaxia-2.7.0-py2.7.egg/zhuaxia/threadpool.py", line 37, in run
    func(*args, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/zhuaxia-2.7.0-py2.7.egg/zhuaxia/downloader.py", line 129, in download_single_song
    download_by_url(song.dl_link, mp3_file, show_progress=True, proxy= get_proxy(song))
  File "/usr/local/lib/python2.7/dist-packages/zhuaxia-2.7.0-py2.7.egg/zhuaxia/downloader.py", line 105, in download_by_url
    for chunk in r.iter_content(1024):
  File "/home/xiangru/.local/lib/python2.7/site-packages/requests/models.py", line 657, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/xiangru/.local/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 326, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/xiangru/.local/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 282, in read
    data = self._fp.read(amt)
  File "/usr/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
error: [Errno 104] Connection reset by peer
~~~

**Comment by lianxiangru** [comment]
@sk1418 
我发现某些下载reset之后其他的下载还在继续，应该是没有ban ip。我出现这种情况比较频繁不知道是不是跟我在美国下载有关。

**Comment by sk1418** [comment]
@lianxiangru  你是没挂代理下载的吧? 是不是进度条不动会比较久?

**Comment by lianxiangru** [comment]
@sk1418 
reset的就永远不动了。。没reset的动的还挺快的。。看速度有500-1000k/s...

**Comment by lianxiangru** [comment]
@sk1418 没挂代理

**Comment by sk1418** [comment]
@lianxiangru  I added a timeout (30 seconds) for mp3 downloading, and 晕,怎么写en了...  如果timeout了, 就重新下载当前文件, 最多重试5次. 目前这个30 和5都是hardcoded, 我觉得没什么必要弄成可设置的.

已经push到bleeding branch 我自己把timeout设置成非常小的值测试,好像是可以. 你可以再测试下你的实际应用. 另外在下载时, 关注下百分比等是不是正确,我自己测试数字蹦的太快..;-) 

bleeding branch里还有个其它的与此issue不相干的改动. 总之你测试下, 如果没什么问题, 我就merge进master.

谢谢.

**Comment by lianxiangru** [comment]
@sk1418 That's great! 我一会回家测试下

**Comment by lianxiangru** [comment]
@sk1418 Just tested it for about an hour. It works perfectly!!!! Thanks!

BTW, how about the incremental downloading feature I mentioned in another issue?

**Comment by sk1418** [comment]
还存在问题 [#23] 
到周末前不一定有时间弄zhuaxia, 等我找时间看下.

regarding another issue, cpu能多线程, 我不行  :-)  所以这个issue说这个issue的事. 一件件办.

**Comment by lianxiangru** [comment]
@sk1418 Cool. Thank you a lot!

**Comment by sk1418** [comment]
@lianxiangru 


目前怀疑那些没下载完成的是因为5次重试用光后,仍未成功完成下载情况下的残留文件.  针对这个情况从用户角度说, 做了以下修正:

- 5次retries 后仍未成功下载的歌曲将在输出里用红色显示
- 5次retries 后仍未成功下载的歌曲, 不完整的文件将被删除, 但MP3下载失败后,如果有`-l`选项, 歌词会照样下载
- 增加了下载的log信息(debug level)

另外建议你`~/.zhuaxia/zhuaxia.conf` 里设置`log.level.file = DEBUG` 这样当你某首歌下载时候有问题, 可以在log文件里找这个歌名相关的log, 贴过来,便于问题分析.

所有这些都已经push到了bleeding, 请你再测试下.

谢谢

**Comment by lianxiangru** [comment]
Hi, @sk1418 刚更新测试了一下，还是有没下载完整的歌曲存在。如图
![screenshot from 2015-11-17 18-22-42](https://cloud.githubusercontent.com/assets/8991941/11228087/5098202a-8d58-11e5-944c-934f119a9c2a.png)

DEBUG信息：
~~~
2015-11-17 18:18:53,976 - DEBUG - Log system setup successfully
2015-11-17 18:18:53,977 - DEBUG - hq:True
2015-11-17 18:18:53,977 - DEBUG - inFile:
2015-11-17 18:18:53,977 - DEBUG - inUrl:http://music.163.com/#/album?id=3201079
2015-11-17 18:18:53,977 - DEBUG - needProxyPool:False
2015-11-17 18:18:53,977 - DEBUG - dl_lyric:False
2015-11-17 18:18:53,978 - DEBUG - processing 163 url: "http://music.163.com/#/album?id=3201079"
2015-11-17 18:18:53,979 - DEBUG - [易]开始初始化专辑[3201079]
2015-11-17 18:18:54,565 - DEBUG - [易]创建专辑目录[/home/xiangru/Music/By2_Cat and Mouse]
2015-11-17 18:18:54,565 - DEBUG - [易]下载专辑[Cat and Mouse]封面
2015-11-17 18:18:56,134 - INFO - 解析: "[易] #/album?id=3201079" ..... [专辑] By2 => Cat and Mouse
    |-> [曲目] Cat and Mouse
    |-> [曲目] 当时的我们
    |-> [曲目] 爱我就大声说
    |-> [曲目] 温柔最痛
    |-> [曲目] 那年下雪的时候
    |-> [曲目] 你骗我
    |-> [曲目] 超勇敢
    |-> [曲目] 你没爱过我
    |-> [曲目] 怎样说清此刻的心情
2015-11-17 18:18:56,134 - INFO -  下载任务总数: 9 
 3秒后开始下载
2015-11-17 18:18:59,137 - DEBUG - init thread pool (7) for downloading
2015-11-17 18:18:59,141 - DEBUG - Start downloading
2015-11-17 18:18:59,141 - DEBUG - [DL_Song] start downloading: /home/xiangru/Music/By2_Cat and Mouse/By2_Cat and Mouse.mp3 retry: 1
2015-11-17 18:18:59,142 - DEBUG - [DL_Song] start downloading: /home/xiangru/Music/By2_Cat and Mouse/By2_当时的我们.mp3 retry: 1
2015-11-17 18:18:59,147 - DEBUG - [DL_Song] start downloading: /home/xiangru/Music/By2_Cat and Mouse/By2_爱我就大声说.mp3 retry: 1
2015-11-17 18:18:59,147 - DEBUG - [DL_Song] start downloading: /home/xiangru/Music/By2_Cat and Mouse/By2_温柔最痛.mp3 retry: 1
2015-11-17 18:18:59,148 - DEBUG - [DL_Song] start downloading: /home/xiangru/Music/By2_Cat and Mouse/By2_那年下雪的时候.mp3 retry: 1
2015-11-17 18:18:59,148 - DEBUG - [DL_Song] start downloading: /home/xiangru/Music/By2_Cat and Mouse/By2_你骗我.mp3 retry: 1
2015-11-17 18:18:59,150 - DEBUG - [DL_Song] start downloading: /home/xiangru/Music/By2_Cat and Mouse/By2_超勇敢.mp3 retry: 1
2015-11-17 18:19:20,866 - DEBUG - [DL_Song] Finished: /home/xiangru/Music/By2_Cat and Mouse/By2_超勇敢.mp3
2015-11-17 18:19:20,866 - DEBUG - [DL_Song] start downloading: /home/xiangru/Music/By2_Cat and Mouse/By2_你没爱过我.mp3 retry: 1
2015-11-17 18:20:02,784 - DEBUG - [DL_URL] downloading song By2_那年下雪的时候.mp3 timeout!
2015-11-17 18:20:02,784 - DEBUG - [DL_Song] remove incompleted file : /home/xiangru/Music/By2_Cat and Mouse/By2_那年下雪的时候.mp3
2015-11-17 18:20:02,784 - DEBUG - [DL_Song] start downloading: /home/xiangru/Music/By2_Cat and Mouse/By2_那年下雪的时候.mp3 retry: 2
2015-11-17 18:20:04,096 - DEBUG - [DL_URL] downloading song By2_爱我就大声说.mp3 timeout!
2015-11-17 18:20:04,096 - DEBUG - [DL_Song] remove incompleted file : /home/xiangru/Music/By2_Cat and Mouse/By2_爱我就大声说.mp3
2015-11-17 18:20:04,097 - DEBUG - [DL_Song] start downloading: /home/xiangru/Music/By2_Cat and Mouse/By2_爱我就大声说.mp3 retry: 2
2015-11-17 18:20:04,294 - DEBUG - [DL_URL] downloading song By2_Cat and Mouse.mp3 timeout!
2015-11-17 18:20:04,295 - DEBUG - [DL_Song] remove incompleted file : /home/xiangru/Music/By2_Cat and Mouse/By2_Cat and Mouse.mp3
2015-11-17 18:20:04,295 - DEBUG - [DL_Song] start downloading: /home/xiangru/Music/By2_Cat and Mouse/By2_Cat and Mouse.mp3 retry: 2
2015-11-17 18:20:05,592 - DEBUG - [DL_Song] Finished: /home/xiangru/Music/By2_Cat and Mouse/By2_温柔最痛.mp3
2015-11-17 18:20:05,593 - DEBUG - [DL_Song] start downloading: /home/xiangru/Music/By2_Cat and Mouse/By2_怎样说清此刻的心情.mp3 retry: 1
2015-11-17 18:20:09,612 - DEBUG - [DL_URL] downloading song By2_当时的我们.mp3 timeout!
2015-11-17 18:20:09,612 - DEBUG - [DL_Song] remove incompleted file : /home/xiangru/Music/By2_Cat and Mouse/By2_当时的我们.mp3
2015-11-17 18:20:09,613 - DEBUG - [DL_Song] start downloading: /home/xiangru/Music/By2_Cat and Mouse/By2_当时的我们.mp3 retry: 2
2015-11-17 18:20:09,752 - DEBUG - [DL_URL] downloading song By2_你骗我.mp3 timeout!
2015-11-17 18:20:09,753 - DEBUG - [DL_Song] remove incompleted file : /home/xiangru/Music/By2_Cat and Mouse/By2_你骗我.mp3
2015-11-17 18:20:09,753 - DEBUG - [DL_Song] start downloading: /home/xiangru/Music/By2_Cat and Mouse/By2_你骗我.mp3 retry: 2
2015-11-17 18:20:10,352 - DEBUG - [DL_URL] downloading song By2_你没爱过我.mp3 timeout!
2015-11-17 18:20:10,352 - DEBUG - [DL_Song] remove incompleted file : /home/xiangru/Music/By2_Cat and Mouse/By2_你没爱过我.mp3
2015-11-17 18:20:10,353 - DEBUG - [DL_Song] start downloading: /home/xiangru/Music/By2_Cat and Mouse/By2_你没爱过我.mp3 retry: 2
2015-11-17 18:21:22,608 - DEBUG - [DL_Song] Finished: /home/xiangru/Music/By2_Cat and Mouse/By2_怎样说清此刻的心情.mp3
2015-11-17 18:21:55,794 - DEBUG - [DL_Song] Finished: /home/xiangru/Music/By2_Cat and Mouse/By2_你骗我.mp3
2015-11-17 18:22:00,287 - DEBUG - [DL_Song] Finished: /home/xiangru/Music/By2_Cat and Mouse/By2_当时的我们.mp3
2015-11-17 18:22:00,378 - DEBUG - [DL_Song] Finished: /home/xiangru/Music/By2_Cat and Mouse/By2_Cat and Mouse.mp3
2015-11-17 18:22:09,342 - DEBUG - [DL_Song] Finished: /home/xiangru/Music/By2_Cat and Mouse/By2_那年下雪的时候.mp3
2015-11-17 18:22:14,105 - DEBUG - [DL_Song] Finished: /home/xiangru/Music/By2_Cat and Mouse/By2_爱我就大声说.mp3
2015-11-17 18:22:17,270 - DEBUG - [DL_Song] Finished: /home/xiangru/Music/By2_Cat and Mouse/By2_你没爱过我.mp3
~~~

**Comment by sk1418** [comment]
@lianxiangru 
你是说"超勇敢"那个吗? 那个是正常下载,就那么小 :-( 你看log 一次就下载完了. 我怀疑是不是这个歌有问题.  98k, 会不会是返回的某个html页面? 你用vim打开这个文件看看..  或者就下载这首歌试试

今天晚了, 如果你那边测试有困难, 改天我下载下这个专辑试试. 看log一切是正常..

**Comment by lianxiangru** [comment]
@sk1418 确实是没下载完的音频文件。。打开可以播放前两秒orz

**Comment by sk1418** [comment]
@lianxiangru 
我测试了你的例子, 都完全下载了. 但你说的情况, 确实存在. 尤其是我找了个100首歌的大歌单, 全部完成后,有3,4首不完整. 这是不挂代理的情况.

奇怪的是, 这个不完整的下载, 看起来一切是正常的, zhuaxia把整个资源作为个stream, 每次取1024字节, 读光为止. 这些没完成的mp3, 没有任何错误信息, 看起来就是读完了. 所以要么是requests lib的bug 要么就是服务器有点什么问题. 

我测试了套个session等方式,结果仍有未完成的文件.

还有个测试没弄就是不用requests库, 自己写个下载, 但我读requests库代码下载的那部分, 和我要实现的方式应该一样的. 回头我测下吧, 至少是能排除是不是163服务器的事.

**Comment by lianxiangru** [comment]
@sk1418 ok. 谢谢！

**Comment by sk1418** [comment]
@lianxiangru  我新写了一个只用标准库的下载函数. 我自己用代理服务器, 下载一个100首的歌单 (http://music.163.com/#/playlist?id=97030999) 所有歌曲都完整下载.  又测试了几个歌单也没问题. 

我已经push到了bleeding. 你再测试下你那边情况吧.

**Comment by lianxiangru** [comment]
@sk1418 That's just terrific! I'll try it!

**Comment by lianxiangru** [comment]
@sk1418  测试了一下，我觉得现在下载应该没有什么问题了。谢谢！！！

**Comment by sk1418** [comment]
merged into master. release v2.8.0
