### ISSUE TITLE
Error with music.163.com artist querying.

### ISSUE THREAD

**Issue by Jonasmaster123** [sk1418/zhuaxia#29]
Trying to download the top songs of an artist results in an error. The used python version is 2.7.10 and everything else seems to run fine for now.

--------- RUN COMMAND TYPE ---------
zx -H http://music.163.com/artist?id=XXXXX
('XXXXX' needs to be replaced with artist number)

--------- OUTPUT ---------
Traceback (most recent call last):
  File "/usr/bin/zx", line 4, in <module>
    __import__('pkg_resources').run_script('zhuaxia==3.0.3', 'zx')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 729, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1642, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/zhuaxia-3.0.3-py2.7.egg/EGG-INFO/scripts/zx", line 122, in <module>
    commander.shall_I_begin(option)
  File "/usr/lib/python2.7/site-packages/zhuaxia-3.0.3-py2.7.egg/zhuaxia/commander.py", line 70, in shall_I_begin
    from_url_163(m163, option.inUrl)
  File "/usr/lib/python2.7/site-packages/zhuaxia-3.0.3-py2.7.egg/zhuaxia/commander.py", line 135, in from_url_163
    topsong= netease.NeteaseTopSong(m163, url)
  File "/usr/lib/python2.7/site-packages/zhuaxia-3.0.3-py2.7.egg/zhuaxia/netease.py", line 174, in __init__
    self.init_topsong()
  File "/usr/lib/python2.7/site-packages/zhuaxia-3.0.3-py2.7.egg/zhuaxia/netease.py", line 180, in init_topsong
    song = NeteaseSong(self.handler, song_json=jsong)
  File "/usr/lib/python2.7/site-packages/zhuaxia-3.0.3-py2.7.egg/zhuaxia/netease.py", line 62, in __init__
    self.init_by_json(song_json)
  File "/usr/lib/python2.7/site-packages/zhuaxia-3.0.3-py2.7.egg/zhuaxia/netease.py", line 78, in init_by_json
    if js['position']:
KeyError: 'position'

**Comment by sk1418** [comment]
change has been pushed into master. pls test and report result. (or close the issue if it was fixed)

**Comment by Jonasmaster123** [comment]
The artists are now working =) , but the albums are crashing =(.

--------- RUN COMMAND TYPE ---------
zx -H http://music.163.com/album?id=XXXXXX

--------- OUTPUT ---------
Traceback (most recent call last):
  File "/usr/bin/zx", line 4, in <module>
    __import__('pkg_resources').run_script('zhuaxia==3.0.4', 'zx')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 729, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1642, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/zhuaxia-3.0.4-py2.7.egg/EGG-INFO/scripts/zx", line 122, in <module>
    commander.shall_I_begin(option)
  File "/usr/lib/python2.7/site-packages/zhuaxia-3.0.4-py2.7.egg/zhuaxia/commander.py", line 70, in shall_I_begin
    from_url_163(m163, option.inUrl)
  File "/usr/lib/python2.7/site-packages/zhuaxia-3.0.4-py2.7.egg/zhuaxia/commander.py", line 111, in from_url_163
    album = netease.NeteaseAlbum(m163, url)
  File "/usr/lib/python2.7/site-packages/zhuaxia-3.0.4-py2.7.egg/zhuaxia/netease.py", line 115, in __init__
    self.init_album()
  File "/usr/lib/python2.7/site-packages/zhuaxia-3.0.4-py2.7.egg/zhuaxia/netease.py", line 128, in init_album
    song.group_dir = self.artist_name + u'_' + self.album_name
AttributeError: 'NeteaseAlbum' object has no attribute 'artist_name'

**Comment by sk1418** [comment]
fixed pushed into master. pls pull the latest version and test again. thx

**Comment by Jonasmaster123** [comment]
Everything seems to run fine now. Thanks!
