### ISSUE TITLE
Download over proxy manjaro fails + script is incredibly slow (long gives no reaction)

### ISSUE THREAD

**Issue by VortekDesign** [sk1418/zhuaxia#34]
Traceback (most recent call last):
  File "/usr/bin/zx", line 122, in <module>
    commander.shall_I_begin(option)
  File "/usr/lib/python2.7/site-packages/zhuaxia/commander.py", line 70, in shall_I_begin
    from_url_163(m163, option.inUrl)
  File "/usr/lib/python2.7/site-packages/zhuaxia/commander.py", line 111, in from_url_163
    album = netease.NeteaseAlbum(m163, url)
  File "/usr/lib/python2.7/site-packages/zhuaxia/netease.py", line 128, in **init**
    self.init_album()
  File "/usr/lib/python2.7/site-packages/zhuaxia/netease.py", line 141, in init_album
    song = NeteaseSong(self.handler, song_json=jsong)
  File "/usr/lib/python2.7/site-packages/zhuaxia/netease.py", line 67, in **init**
    self.init_by_json(song_json)
  File "/usr/lib/python2.7/site-packages/zhuaxia/netease.py", line 106, in init_by_json
    self.dl_link = self.handler.get_mp3_dl_link(self.song_id, bitrate)
  File "/usr/lib/python2.7/site-packages/zhuaxia/netease.py", line 285, in get_mp3_dl_link
    r = self.read_link(result)
  File "/usr/lib/python2.7/site-packages/zhuaxia/netease.py", line 243, in read_link
    retVal =  requests.get(link, headers=self.HEADERS, proxies=requests_proxy)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, *_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, *_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, *_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='m10.music.126.net', port=80): Max retries exceeded with url: /20160424014715/0faafb39798b03d8cef7d475b33db280/ymusic/5271/40fb/de9a/ffa3da653b20581cf84b04af1bf94515.mp3 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7ff380a79190>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by sk1418** [comment]
provide the link you had problem pls
