### ISSUE TITLE
ubuntu 14.04 cannot concatenate 'str' and 'NoneType' objects

### ISSUE THREAD

**Issue by judi0713** [sk1418/zhuaxia#39]
Traceback (most recent call last):
  File "/usr/local/bin/zx", line 5, in <module>
    pkg_resources.run_script('zhuaxia==3.1.1', 'zx')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/zhuaxia-3.1.1-py2.7.egg/EGG-INFO/scripts/zx", line 119, in <module>
    option.debug_me()
  File "/usr/local/lib/python2.7/dist-packages/zhuaxia-3.1.1-py2.7.egg/zhuaxia/option.py", line 24, in debug_me
    LOG.debug( "proxy:"+ self.proxy)
TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by sk1418** [comment]
oops.... working on it...
