### ISSUE TITLE
xiami.com 无法识别

### ISSUE THREAD

**Issue by yellowxiao** [sk1418/zhuaxia#42]
安装后点击zx未出现conj文件，并显示parameters are missing。但使用可以成功解析music.163.com
点击解析虾米时，出现以下错误。
Traceback (most recent call last):
  File "/usr/local/bin/zx", line 4, in <module>
    **import**('pkg_resources').run_script('zhuaxia==3.1.2', 'zx')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/**init**.py", line 726, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/**init**.py", line 1651, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/zhuaxia-3.1.2-py2.7.egg/EGG-INFO/scripts/zx", line 122, in <module>
    commander.shall_I_begin(option)
  File "/usr/local/lib/python2.7/site-packages/zhuaxia-3.1.2-py2.7.egg/zhuaxia/commander.py", line 68, in shall_I_begin
    from_url_xm(xiami_obj, option.inUrl)
  File "/usr/local/lib/python2.7/site-packages/zhuaxia-3.1.2-py2.7.egg/zhuaxia/commander.py", line 175, in from_url_xm
    song = xm.XiamiSong(xm_obj, url=url)
  File "/usr/local/lib/python2.7/site-packages/zhuaxia-3.1.2-py2.7.egg/zhuaxia/xiami.py", line 59, in **init**
    self.song_id = re.search(r'(?<=/song/)\d+', url).group(0)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by sk1418** [comment]
请给出你有问题的链接.. 我下班回去可以看看.  但是最近xiami不知做了什么, 通过浏览器+国内代理访问, 每次都出现验证码, 即使给正确的, 也无法进入. 所以能不能找到问题还不知道, 现在很难调试虾米.
但是通过错误信息, 好像你给的虾米的链接不太对. 请贴链接.

**Comment by yellowxiao** [comment]
你好，我检查发现好像确实链接有问题，感谢！没想到能这么快收到回复！
不过我发现在点击虾米专辑选项下载特定歌曲时，歌曲名也会变成专辑名。

**Comment by yellowxiao** [comment]
刚刚有问题的链接在此
http://www.xiami.com/song/1770341643?spm=a1z1s.3521865.23309997.55.JLvShP
