### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by shubo83** [sk1418/zhuaxia#54]
zx -i http://music.163.com/\#/playlist\?id\=39554181

报错如下：

Traceback (most recent call last):
  File "/usr/local/bin/zx", line 4, in <module>
    __import__('pkg_resources').run_script('zhuaxia==3.2.1', 'zx')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1667, in run_script
    exec(code, namespace, namespace)
  File "/Library/Python/2.7/site-packages/zhuaxia-3.2.1-py2.7.egg/EGG-INFO/scripts/zx", line 122, in <module>
    commander.shall_I_begin(option)
  File "/Library/Python/2.7/site-packages/zhuaxia-3.2.1-py2.7.egg/zhuaxia/commander.py", line 70, in shall_I_begin
    from_url_163(m163, option.inUrl)
  File "/Library/Python/2.7/site-packages/zhuaxia-3.2.1-py2.7.egg/zhuaxia/commander.py", line 123, in from_url_163
    playlist = netease.NeteasePlayList(m163, url)
  File "/Library/Python/2.7/site-packages/zhuaxia-3.2.1-py2.7.egg/zhuaxia/netease.py", line 174, in __init__
    self.init_playlist()
  File "/Library/Python/2.7/site-packages/zhuaxia-3.2.1-py2.7.egg/zhuaxia/netease.py", line 180, in init_playlist
    song = NeteaseSong(self.handler, song_json=jsong)
  File "/Library/Python/2.7/site-packages/zhuaxia-3.2.1-py2.7.egg/zhuaxia/netease.py", line 74, in __init__
    self.init_by_json(song_json)
  File "/Library/Python/2.7/site-packages/zhuaxia-3.2.1-py2.7.egg/zhuaxia/netease.py", line 87, in init_by_json
    self.album_name = util.decode_html(js['album']['name'])
  File "/Library/Python/2.7/site-packages/zhuaxia-3.2.1-py2.7.egg/zhuaxia/util.py", line 56, in decode_html
    return HTMLParser.HTMLParser().unescape(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/HTMLParser.py", line 448, in unescape
    if '&' not in s:
TypeError: argument of type 'NoneType' is not iterable

**Comment by sk1418** [comment]
fixed in all branches.
